---
- name: Install the EPEL repository
  yum:
    name: '{{ epel_package_url }}'
    state: present

- name: Install the support tools
  yum:
    name: '{{ item }}'
    state: present
  with_items:
   - tmux
   - htop
   - vim
   - nc
   - telnet
   - net-tools
   - lsof
   - mc
   - wget
   - unzip
   - ntp
   - curl

- name: Set shell colors
  template:
    src: colorcmd.sh.j2
    dest: /etc/profile.d/colorcmd.sh



